version: '3.1'

services:
  db-postagens:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
      - MYSQL_DATABASE=dbpostagens
    ports:
      - "3306:3306"
    networks:
      - geral-network
  mongodb:
    image: mongo
    restart: always
    networks:
      - geral-network
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    restart: always
    networks:
      - geral-network
    ports:
      - "9200:9200"
      - "9300:9300"
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
    networks:
      - geral-network
    ports:
      - "4566:4566"

networks:
  geral-network:
    driver: bridge